batch_size: 16
workers: 8
nepoch: 800

model_name: PointAttN_baseline_cd
# model_name: PointAttN_baseline_hcd
# model_name: PointAttN_sfa_cd
# model_name: PointAttN_sfa_hcd

# python train.py -c PointAttN.yaml
# python test_pcn.py -c PointAttN.yaml

load_model:
# load_model: ./log/PointAttN_baseline_cd_cd_debug_pcn/best_cd_p_coarse_network.pth   
# load_model: ./log/PointAttN_baseline_cd_cd_debug_pcn/network.pth 

# load_model: ./log/PointAttN_baseline_hcd_cd_debug_pcn/best_cd_p_coarse_network.pth   
# load_model: ./log/PointAttN_baseline_hcd_cd_debug_pcn/network.pth 

# load_model: ./log/PointAttN_sfa_cd_cd_debug_pcn/best_cd_p_network.pth   
# load_model: ./log/PointAttN_sfa_cd_cd_debug_pcn/network.pth 

# load_model: ./log/PointAttN_sfa_hcd_cd_debug_pcn/best_cd_p_network.pth   
# load_model: ./log/PointAttN_sfa_hcd_cd_debug_pcn/network.pth 

start_epoch: 0
num_points: 2048
work_dir: log/
flag: debug
loss: cd #cd
manual_seed: 1748
step_interval_to_print: 100
epoch_interval_to_save: 1
epoch_interval_to_val: 1

lr: 0.0001
lr_decay: True
lr_decay_interval: 40
lr_decay_rate: 0.7
lr_step_decay_epochs: null
lr_step_decay_rates: null
lr_clip: 1.e-6
optimizer: Adam
weight_decay: 0
betas: 0.9, 0.999

device: '0'
dataset: 'pcn'
pcnpath: $PATH/ShapeNetCompletion
c3dpath: $PATH/shapenet
# test
save_vis: True
